### ISSUE TITLE
Memory leak in extremely hot loops

### ISSUE THREAD

**Issue by BlueCyro** [clibequilibrium/Tracy-CSharp#24]
Hiya, I wanted to instrument my code using this tool, but it appears to cause a memory leak in extremely hot loops. This is reproduceable by simply removing the `Thread.Sleep` in the while loop within the HelloWorld example. This will swiftly allocate nearly all of your RAM in a matter of seconds. I am currently unable to use this in my project due to the tightness of the loops I'm measuring.

Using the PInvokes directly also results in a very fast memory leak.

**Comment by clibequilibrium** [comment]
> Hiya, I wanted to instrument my code using this tool, but it appears to cause a memory leak in extremely hot loops. This is reproduceable by simply removing the `Thread.Sleep` in the while loop within the HelloWorld example. This will swiftly allocate nearly all of your RAM in a matter of seconds. I am currently unable to use this in my project due to the tightness of the loops I'm measuring.
> 
> Using the PInvokes directly also results in a very fast memory leak.

Hi, not sure I can reproduce it. 

On my end removed Thread.Sleep and connected Tracy 0.10 

![image](https://github.com/clibequilibrium/Tracy-CSharp/assets/105135724/3be73117-9f5a-4782-ad95-9af1c82bb915)

Could you make a repro project? 
Thanks.

**Comment by BlueCyro** [comment]
Apologies for the initially unclear issue. Here's a sample I've made. I neglected to mention that I also commented out `Delay()` as well.

[HelloWorld.zip](https://github.com/clibequilibrium/Tracy-CSharp/files/15260626/HelloWorld.zip)

Using any of the tracing methods either from the provided profiler class or manually calling the PInvoke methods in a super hot loop results in much the same outcome as this artificial example.

**Comment by clibequilibrium** [comment]
> Apologies for the initially unclear issue. Here's a sample I've made. I neglected to mention that I also commented out `Delay()` as well.
> 
> [HelloWorld.zip](https://github.com/clibequilibrium/Tracy-CSharp/files/15260626/HelloWorld.zip)
> 
> Using any of the tracing methods either from the provided profiler class or manually calling the PInvoke methods in a super hot loop results in much the same outcome as this artificial example.

Interesting. Could you try using BeginEvent that does not use colorType for now and let me know if you still have the leak ? 
I am investigating 

EDIT: happens on both, interesting

**Comment by clibequilibrium** [comment]
@BlueCyro 
actually I think this is expected. If you remove Thread.Sleep(1) then your CPU will try to produce as many events as possible. If you don't have Tracy connected  they won't be consumed and stored in system memory. See I am pushing 1 Gbit of data to Tracy. You need to have Thread.Sleep(1) to cap the capture somehow, 1ms would give you 1000 captures per second, are you sure you need more ?  I see in their .pdf file they also have sleep for at least 1 ms because there have to be at least some work to keep CPU busy, sleep(1) simply emulates that. Can you tell me what is your hot code path look like ? I am curious is to why your App is so fast and wastes CPU cycles. 


Edit: this explains why if you call 2 methods and even though there is no Thread.Sleep(1) there is no memory leak because Delay() method keeps the CPU busy with work, such as generating random value in a for loop.  For example giving your CPU some work won't overload Tracy

```CSharp
  static void ColoredEvent()
    {
        using (Profiler.BeginEvent(colorType: Profiler.ColorType.Aqua))
        {
            Random random = new Random();
            int y = (int)random.NextInt64() / 1;
        }
    }
 ```

![image](https://github.com/clibequilibrium/Tracy-CSharp/assets/105135724/210a3f6f-d687-4611-b8a9-7ead908c95a8)

**Comment by BlueCyro** [comment]
Sure thing, I have a software rasterizer I'm building and I'm attempting to debug an issue where the performance degrades randomly run-to-run.

https://github.com/BlueCyro/Paprika/blob/main/Renderer%2FPixel%20Pusher%2FPaprikaRendererDrawFunctions.cs#L121

This function is called many times a second in a loop from [RenderFrame](https://github.com/BlueCyro/Paprika/blob/main/Renderer%2FPixel%20Pusher%2FPaprikaRenderer.cs#L53) and I need to profile it at full speed to see what's actually happening. The native Tracy library touts only several nanoseconds to log a profiling event, so I am somewhat miffed that a delay is seemingly required.

**Comment by clibequilibrium** [comment]
> Sure thing, I have a software rasterizer I'm building and I'm attempting to debug an issue where the performance degrades randomly run-to-run.
> 
> https://github.com/BlueCyro/Paprika/blob/main/Renderer%2FPixel%20Pusher%2FPaprikaRendererDrawFunctions.cs#L121
> 
> This function is called many times a second in a loop from [RenderFrame](https://github.com/BlueCyro/Paprika/blob/main/Renderer%2FPixel%20Pusher%2FPaprikaRenderer.cs#L53) and I need to profile it at full speed to see what's actually happening. The native Tracy library touts only several nanoseconds to log a profiling event, so I am somewhat miffed that a delay is seemingly required.

Thanks. So this block of code causes the leak ?  https://github.com/BlueCyro/Paprika/blob/e85f546557d031b01125d94588ca8ee1edfb9af4/Renderer/Pixel%20Pusher/PaprikaRenderer.cs#L75

**Comment by BlueCyro** [comment]
> > Sure thing, I have a software rasterizer I'm building and I'm attempting to debug an issue where the performance degrades randomly run-to-run.
> > https://github.com/BlueCyro/Paprika/blob/main/Renderer%2FPixel%20Pusher%2FPaprikaRendererDrawFunctions.cs#L121
> > This function is called many times a second in a loop from [RenderFrame](https://github.com/BlueCyro/Paprika/blob/main/Renderer%2FPixel%20Pusher%2FPaprikaRenderer.cs#L53) and I need to profile it at full speed to see what's actually happening. The native Tracy library touts only several nanoseconds to log a profiling event, so I am somewhat miffed that a delay is seemingly required.
> 
> Thanks. So this block of code causes the leak ? https://github.com/BlueCyro/Paprika/blob/e85f546557d031b01125d94588ca8ee1edfb9af4/Renderer/Pixel%20Pusher/PaprikaRenderer.cs#L75

It depends on how quickly it executes (can vary depending on how many tris there are), but I wanted to insert events for that area and also within the `DrawPinedaTriangleSIMD` function so I can see how long each part of my program takes to execute individually. This is an attempt to diagnose different parts of my program to see what makes the performance vary so much run-to-run. I tested it with a 1.6m tri model, which is where I noticed that all of my system ram gets eaten up in no time when I insert calls to tracy.

Also do note that repo is for learning program structure and stuff, so it's probably a little messy :p

**Comment by clibequilibrium** [comment]
> > > Sure thing, I have a software rasterizer I'm building and I'm attempting to debug an issue where the performance degrades randomly run-to-run.
> > > https://github.com/BlueCyro/Paprika/blob/main/Renderer%2FPixel%20Pusher%2FPaprikaRendererDrawFunctions.cs#L121
> > > This function is called many times a second in a loop from [RenderFrame](https://github.com/BlueCyro/Paprika/blob/main/Renderer%2FPixel%20Pusher%2FPaprikaRenderer.cs#L53) and I need to profile it at full speed to see what's actually happening. The native Tracy library touts only several nanoseconds to log a profiling event, so I am somewhat miffed that a delay is seemingly required.
> > 
> > 
> > Thanks. So this block of code causes the leak ? https://github.com/BlueCyro/Paprika/blob/e85f546557d031b01125d94588ca8ee1edfb9af4/Renderer/Pixel%20Pusher/PaprikaRenderer.cs#L75
> 
> It depends on how quickly it executes (can vary depending on how many tris there are), but I wanted to insert events for that area and also within the `DrawPinedaTriangleSIMD` function so I can see how long each part of my program takes to execute individually. This is an attempt to diagnose different parts of my program to see what makes the performance vary so much run-to-run. I tested it with a 1.6m tri model, which is where I noticed that all of my system ram gets eaten up in no time when I insert calls to tracy.
> 
> Also do note that repo is for learning program structure and stuff, so it's probably a little messy :p

So you would be sending 1.6m request every frame ? Could you maybe try to send 1 request per frame but then use multiple scoped zones ?

**Comment by BlueCyro** [comment]
Could you elaborate a little bit on 'scoped zones'? I was looking to collect extremely fine execution timing info so I can see which parts of the program start accumulating time on bad runs. Would what you're suggesting allow that in some form?

**Comment by clibequilibrium** [comment]
> Could you elaborate a little bit on 'scoped zones'? I was looking to collect extremely fine execution timing info so I can see which parts of the program start accumulating time on bad runs. Would what you're suggesting allow that in some form?

If you want to measure every tri in 1.6m model you might be hitting limitations? 
![image](https://github.com/clibequilibrium/Tracy-CSharp/assets/105135724/17df65cd-ae48-49dd-b26d-e97b51333b49)

I still don't understand how many events are you trying to collect, but you can try to picture if you are trying to collect 1.6m every frame and 1 second passes that would be 96 million events just at 60 fps, now if you don't have VSync then you try to collect as fast as possible and it will be more than 96 million . Now let's assume each caputre is roughly 100 bytes, that's 9.6 GB right away in just 1 second.

**Comment by BlueCyro** [comment]
That makes sense. I was just initially under the impression that Tracy was this godlike thing that took like zero performance lol. I'm still a little unsure what you mean by '1 frame with multiple scoped zones' though.

**Comment by clibequilibrium** [comment]
> That makes sense. I was just initially under the impression that Tracy was this godlike thing that took like zero performance lol. I'm still a little unsure what you mean by '1 frame with multiple scoped zones' though.

There is a small overhead in execution but don't forget that each snapshot is stored in a memory. There is a reason why GPU exist and you can profile those with Renderdoc and Nvidia Nsight. 

![image](https://github.com/clibequilibrium/Tracy-CSharp/assets/105135724/3aa60813-049f-4ce8-91b1-70b3381fec0b)

But since you are writing a software rasterizer , you can have a global frame capture, and then maybe capture first 100k tris instead of 1.6 million and see how it works ?

What I meant about zones is that you can create as many zones as you like to make it granular as you want, just make sure you are not capturing millions of them a second. 

So try to have a frame zone, then the zone that captures  ``DrawPinedaTriangleSIMD`` but let's say capture first 100k, then you can wait a bit and capture the same 100k again and see how they deviate. Does that make sense ?

I don't think anyway you can go over each of 1.6 million profiler data points to see the difference

**Comment by BlueCyro** [comment]
Okay, I'll try that. Thank you very much. This issue likely doesn't need to strictly be open anymore. Thanks for initially looking into it.
