### ISSUE TITLE
Corrupted plots using the new examples.

### ISSUE THREAD

**Issue by BlueCyro** [clibequilibrium/Tracy-CSharp#34]
Heya, I've got some issue going on with the new profiler examples provided in this repo.

Specifically, when you use the new plot examples you'll end up getting corrupted plot names. I suspect this is due to the CStrings being disposed of immediately before the C++ side can read them.

The new examples seem to dispose of CStrings alarmingly quickly, and so I'm a little worried about how widespread this issue is throughout the examples. Disposing of them immediately.

Here you can see the names of the plot being corrupted (there is only supposed to be one) and this causes Tracy to output more and more the longer the program continues to run. My profiling zones follow the same principles as the ones in the example profiler:
![image](https://github.com/user-attachments/assets/2f9b1afe-a98e-4ad4-ad48-7ef6788d0e72)

## Reproduction
1) Lift one of the plotting functions out of the current examples.
2) Plot in a loop with a thread delay to test it
3) Note that multiple plots will appear in Tracy.

Here's a simple top-level statement that reproduces the issue cleanly (note that you may have to run it multiple times, as the issue can be sporadic)

```csharp
using bottlenoselabs.C2CS.Runtime;
using static Tracy.PInvoke;

static async Task test()
{
    for (int i = 0; i < 200; i++)
    {
        Thread.Sleep(600);
        using CString newString = CString.FromString("TEST PLOT");
        TracyEmitPlotInt(newString, i);
    }
}


await test();
```

This issue is exacerbated if you perform more operations such as profiling a zone or emitting text, which will cause the plots to become more and more corrupted and numerous.

**Comment by clibequilibrium** [comment]
@Mervill  could you take a look please?

We might need to fall back to the cache approach and Dispose the profiler via ``using`` statement

**Comment by clibequilibrium** [comment]
> Heya, I've got some issue going on with the new profiler examples provided in this repo.
> 
> Specifically, when you use the new plot examples you'll end up getting corrupted plot names. I suspect this is due to the CStrings being disposed of immediately before the C++ side can read them.
> 
> The new examples seem to dispose of CStrings alarmingly quickly, and so I'm a little worried about how widespread this issue is throughout the examples. Disposing of them immediately.
> 
> Here you can see the names of the plot being corrupted (there is only supposed to be one) and this causes Tracy to output more and more the longer the program continues to run. My profiling zones follow the same principles as the ones in the example profiler: ![image](https://private-user-images.githubusercontent.com/9770110/370947683-2f9b1afe-a98e-4ad4-ad48-7ef6788d0e72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzU2MjAsIm5iZiI6MTcyNzM3NTMyMCwicGF0aCI6Ii85NzcwMTEwLzM3MDk0NzY4My0yZjliMWFmZS1hOThlLTRhZDQtYWQ0OC03ZWY2Nzg4ZDBlNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMTgyODQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjM2YjYxZjk2ZGJlOThiNzQxNmIxYTg1NGYyNDRlNTc1NWJmODM2YTNmNTYxZGJiNmY4MWE4ODkwMmYyZGNhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fbcXBtmXbdLzOydZnF98lkW7xr7uNFBkiQbHF6M1XhI)
> 
> ## Reproduction
> 1. Lift one of the plotting functions out of the current examples.
> 2. Plot in a loop with a thread delay to test it
> 3. Note that multiple plots will appear in Tracy.
> 
> Here's a simple top-level statement that reproduces the issue cleanly (note that you may have to run it multiple times, as the issue can be sporadic)
> 
> ```cs
> using bottlenoselabs.C2CS.Runtime;
> using static Tracy.PInvoke;
> 
> static async Task test()
> {
>     for (int i = 0; i < 200; i++)
>     {
>         Thread.Sleep(600);
>         using CString newString = CString.FromString("TEST PLOT");
>         TracyEmitPlotInt(newString, i);
>     }
> }
> 
> 
> await test();
> ```
> 
> This issue is exacerbated if you perform more operations such as profiling a zone or emitting text, which will cause the plots to become more and more corrupted and numerous.

Thank you for the detailed bug-report.

**Comment by BlueCyro** [comment]
No prob! Forgive the naivety as I'm not experienced with C++ a whole lot, but would it make sense to do a bit more heavy-lifting on that side so that stuff doesn't need to be cached on the C# side? As far as I understand the tracy docs, it appears that most of the frame marking, plotting, etc. all wanna be kept on the stack as much as possible. (I haven't read the Tracy source yet, so forgive the educated guess)

There is a library I've worked with called 'soundpipe' that is written in C and takes a "Create -> Init -> Compute -> Destroy" approach on the C side. Perhaps it would be easier to manage the memory if the C++ side was the one creating and destroying the contexts? That way, you could simply receive a pointer or something that you pass around until you need to pass it back to the C++ side to be destroyed.

If it's fast enough, you could potentially use [SuppressGCTransition](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.suppressgctransitionattribute?view=net-8.0) to reduce the overhead of P/Invoke calls too.

**Comment by BlueCyro** [comment]
> No prob! Forgive the naivety as I'm not experienced with C++ a whole lot, but would it make sense to do a bit more heavy-lifting on that side so that stuff doesn't need to be cached on the C# side? As far as I understand the tracy docs, it appears that most of the frame marking, plotting, etc. all wanna be kept on the stack as much as possible. (I haven't read the Tracy source yet, so forgive the educated guess)
> 
> There is a library I've worked with called 'soundpipe' that is written in C and takes a "Create -> Init -> Compute -> Destroy" approach on the C side. Perhaps it would be easier to manage the memory if the C++ side was the one creating and destroying the contexts? That way, you could simply receive a pointer or something that you pass around until you need to pass it back to the C++ side to be destroyed.
> 
> If it's fast enough, you could potentially use [SuppressGCTransition](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.suppressgctransitionattribute?view=net-8.0) to reduce the overhead of P/Invoke calls too.

Okay, I've done a little bit of looking at the tracy docs and found some things. You can ignore this previous comment.

1) Macros that accept a string literal and a pointer will copy the data in that literal to a temporary internal buffer. You probably do want to pool these, but you could probably increase the efficiency of the pooling by using a more conventional method than the dictionary you had before. (Tbh you could probably just wrap an ArrayPool\<byte\> or something so you can rent/free CString buffers all day, replacing the deallocation that Dispose() on a CString currently does)

2) Macros that only accept a string literal expect that literal to always be available at any point in the program's execution. The documentation suggests defining these somewhere central. Instead of trying to do this manually for the user, making it clear that this is the intended way to do this would probably be the best way here.

3) Some parts of tracy want that same pointer when doing things like marking zone starts and ends, meaning you want that CString to be around until the end of the zone.

**Comment by BlueCyro** [comment]
> > No prob! Forgive the naivety as I'm not experienced with C++ a whole lot, but would it make sense to do a bit more heavy-lifting on that side so that stuff doesn't need to be cached on the C# side? As far as I understand the tracy docs, it appears that most of the frame marking, plotting, etc. all wanna be kept on the stack as much as possible. (I haven't read the Tracy source yet, so forgive the educated guess)
> > There is a library I've worked with called 'soundpipe' that is written in C and takes a "Create -> Init -> Compute -> Destroy" approach on the C side. Perhaps it would be easier to manage the memory if the C++ side was the one creating and destroying the contexts? That way, you could simply receive a pointer or something that you pass around until you need to pass it back to the C++ side to be destroyed.
> > If it's fast enough, you could potentially use [SuppressGCTransition](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.suppressgctransitionattribute?view=net-8.0) to reduce the overhead of P/Invoke calls too.
> 
> Okay, I've done a little bit of looking at the tracy docs and found some things. You can ignore this previous comment.
> 
>     1. Macros that accept a string literal and a pointer will copy the data in that literal to a temporary internal buffer. You probably do want to pool these, but you could probably increase the efficiency of the pooling by using a more conventional method than the dictionary you had before. (Tbh you could probably just wrap an ArrayPool<byte> or something so you can rent/free CString buffers all day, replacing the deallocation that Dispose() on a CString currently does)
> 
>     2. Macros that only accept a string literal expect that literal to always be available at any point in the program's execution. The documentation suggests defining these somewhere central. Instead of trying to do this manually for the user, making it clear that this is the intended way to do this would probably be the best way here.
> 
>     3. Some parts of tracy want that same pointer when doing things like marking zone starts and ends, meaning you want that CString to be around until the end of the zone.

~~Hmm... Instead of pooling buffers, I wonder if would be smarter to allocate the buffers on the stack for the parts of tracy that don't care about the string existing for more than the function call/zone.~~

EDIT: Disregard this as well. If Tracy allocates a temporary buffer, it would probably be slower to copy a string from heap -> stack -> heap, than to just use a heap pool.

**Comment by clibequilibrium** [comment]
> No prob! Forgive the naivety as I'm not experienced with C++ a whole lot, but would it make sense to do a bit more heavy-lifting on that side so that stuff doesn't need to be cached on the C# side? As far as I understand the tracy docs, it appears that most of the frame marking, plotting, etc. all wanna be kept on the stack as much as possible. (I haven't read the Tracy source yet, so forgive the educated guess)
> 
> There is a library I've worked with called 'soundpipe' that is written in C and takes a "Create -> Init -> Compute -> Destroy" approach on the C side. Perhaps it would be easier to manage the memory if the C++ side was the one creating and destroying the contexts? That way, you could simply receive a pointer or something that you pass around until you need to pass it back to the C++ side to be destroyed.
> 
> If it's fast enough, you could potentially use [SuppressGCTransition](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.suppressgctransitionattribute?view=net-8.0) to reduce the overhead of P/Invoke calls too.

Thank you for starting the discussion! You are not wrong by suggesting to maybe do more memory management on unmanaged C/C++ side, but it will go beyond the scope of just a C# wrapper. This is always a challenge when working with managed / unmanaged languages. CString simply allows us to create a copy of a string that won't be subject to GC - ever. If memory allocation in hot path becomes a bottleneck in your app - you might want to consider linear allocator like smmalloc  https://github.com/nxrighthere/Smmalloc-CSharp ; however, for the majority of use cases heap based CString should be just fine and perform alright

**Comment by BlueCyro** [comment]
> > No prob! Forgive the naivety as I'm not experienced with C++ a whole lot, but would it make sense to do a bit more heavy-lifting on that side so that stuff doesn't need to be cached on the C# side? As far as I understand the tracy docs, it appears that most of the frame marking, plotting, etc. all wanna be kept on the stack as much as possible. (I haven't read the Tracy source yet, so forgive the educated guess)
> > There is a library I've worked with called 'soundpipe' that is written in C and takes a "Create -> Init -> Compute -> Destroy" approach on the C side. Perhaps it would be easier to manage the memory if the C++ side was the one creating and destroying the contexts? That way, you could simply receive a pointer or something that you pass around until you need to pass it back to the C++ side to be destroyed.
> > If it's fast enough, you could potentially use [SuppressGCTransition](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.suppressgctransitionattribute?view=net-8.0) to reduce the overhead of P/Invoke calls too.
> 
> Thank you for starting the discussion! You are not wrong by suggesting to maybe do more memory management on unmanaged C/C++ side, but it will go beyond the scope of just a C# wrapper. This is always a challenge when working with managed / unmanaged languages. CString simply allows us to create a copy of a string that won't be subject to GC - ever. If memory allocation in hot path becomes a bottleneck in your app - you might want to consider linear allocator like smmalloc https://github.com/nxrighthere/Smmalloc-CSharp ; however, for the majority of use cases heap based CString should be just fine and perform alright

I can't promise anything, but would it be alright to pull-request some examples of ways to manage the CStrings like how you mentioned sometime? I could be wrong, but the current method of allocating memory via the marshal and deallocating it in rapid succession would start adding up fairly quickly, wouldn't it? Perhaps I have a skewed view of memory allocation, but it sticks out to me still.

Intuitively, my first thought is to create an unmanaged buffer pool - potentially with `NativeMemory.AllignedAlloc` so you can reap the benefits of cache locality - and keep "power pools" (saw this in bepu physics v2) that keep aligned buffers in powers of two and allocate them as demand requires.

Sorry if I'm being a little bit of a nut :p I could move this to a separate discussion issue since I'm diverging from the issue topic a bit

**Comment by clibequilibrium** [comment]
> > > No prob! Forgive the naivety as I'm not experienced with C++ a whole lot, but would it make sense to do a bit more heavy-lifting on that side so that stuff doesn't need to be cached on the C# side? As far as I understand the tracy docs, it appears that most of the frame marking, plotting, etc. all wanna be kept on the stack as much as possible. (I haven't read the Tracy source yet, so forgive the educated guess)
> > > There is a library I've worked with called 'soundpipe' that is written in C and takes a "Create -> Init -> Compute -> Destroy" approach on the C side. Perhaps it would be easier to manage the memory if the C++ side was the one creating and destroying the contexts? That way, you could simply receive a pointer or something that you pass around until you need to pass it back to the C++ side to be destroyed.
> > > If it's fast enough, you could potentially use [SuppressGCTransition](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.suppressgctransitionattribute?view=net-8.0) to reduce the overhead of P/Invoke calls too.
> > 
> > 
> > Thank you for starting the discussion! You are not wrong by suggesting to maybe do more memory management on unmanaged C/C++ side, but it will go beyond the scope of just a C# wrapper. This is always a challenge when working with managed / unmanaged languages. CString simply allows us to create a copy of a string that won't be subject to GC - ever. If memory allocation in hot path becomes a bottleneck in your app - you might want to consider linear allocator like smmalloc https://github.com/nxrighthere/Smmalloc-CSharp ; however, for the majority of use cases heap based CString should be just fine and perform alright
> 
> I can't promise anything, but would it be alright to pull-request some examples of ways to manage the CStrings like how you mentioned sometime? I could be wrong, but the current method of allocating memory via the marshal and deallocating it in rapid succession would start adding up fairly quickly, wouldn't it? Perhaps I have a skewed view of memory allocation, but it sticks out to me still.
> 
> Intuitively, my first thought is to create an unmanaged buffer pool - potentially with `NativeMemory.AllignedAlloc` so you can reap the benefits of cache locality - and keep "power pools" (saw this in bepu physics v2) that keep aligned buffers in powers of two and allocate them as demand requires.
> 
> Sorry if I'm being a little bit of a nut :p I could move this to a separate discussion issue since I'm diverging from the issue topic a bit

Of course! Feel free to build on top of this https://github.com/clibequilibrium/Tracy-CSharp/pull/36 or wait till I close that up. The original Hello World example held the cached string pointers in a Dictionary

**Comment by Mervill** [comment]
@BlueCyro 

By all means tinker with the allocations. But I'd be careful to avoid premature optimizations.

The library is already extreamily performant. There is a cost to marshalling strings into unmanaged memory but it quickly disappears into the margins when the Profiler is deployed into a real world application. The C# runtime keeps memory available for unmanaged interop so I don't think quickly allocating and then freeing the CStrings is causing underlying memory thrashing (i.e. a problem a pool would alleviate). I would hesitate to muck about with byte arrays unless there's hard evidence that it would seriously improve the time to call into Tracy, which again is already extreamily fast.

The `SuppressGCTransition` attribute does look mildly interesting. It's likely the Tracy functions are shorter then the cost of the GC transition like the docs describe. The PInvoke class is generated though so you'd have to look at the generator options.

Optimizing the Tracy strings for cache locality seems nonsensical. We use Tracy to measure the performance of functions, we want _them_ to use the cache so we can get an accurate measurement of their performance. Unless you are in an _incredibly_ hot loop we wont actually be accessing these strings fast enough for cache locality to matter. Again, I'd be open to seeing evidence to the contrary.

If you do want to cache the source location strings, I wrote about that [here](https://github.com/clibequilibrium/Tracy-CSharp/pull/28#issuecomment-2365309609). I'm not opposed to it, and it would totally eliminate the marshalling cost for most calls into `BeginZone`, but you need to make sure you're keying the data in the cache the same way that Tracy does so you don't end up mapping keys incorrectly.
