### ISSUE TITLE
How to enable on-demand profiling?

### ISSUE THREAD

**Issue by Arugin** [clibequilibrium/Tracy-CSharp#37]
Hi,

I am looking into Pinvoke API of this wrapper and can't find anything. Is this possible to enable on-demand profiling on c# side? Or native libraries should be specifically compiled for this?

Thanks!

**Comment by clibequilibrium** [comment]
> Hi,
> 
> I am looking into Pinvoke API of this wrapper and can't find anything. Is this possible to enable on-demand profiling on c# side? Or native libraries should be specifically compiled for this?
> 
> Thanks!

Hi. Check this branch https://github.com/clibequilibrium/Tracy-CSharp/tree/on-demand
