### ISSUE TITLE
Mismatched/randomly-colored & duplicate entries in tracy statistics

### ISSUE THREAD

**Issue by BlueCyro** [clibequilibrium/Tracy-CSharp#40]
Hi again, I'm becoming the <span>#</span>1 issue maker on this repo it seems. ^^;

I've been referencing the new examples (and the previous ones before the CString oopsie) and I think there's something wrong with the way the zone contexts are instantiated.

## Problem

When recreating the "StartZone" method from the profiler class, I was getting weird inconsistencies in the color swatches within Tracy's Statistics menu. Occasionally they will create duplicates and randomly switch colors. They also don't appear to initially reflect the set color of the zone to begin with.

Here's an example:
![image](https://github.com/user-attachments/assets/fbb05817-925e-448e-aae9-893556c56c87)

Here you can see that the "My Custom Event Name" event is a distinctly different shade of blue, and is duplicated twice over, with one being green. The ColoredEvent event doesn't match set zone color to begin with entirely.

The following picture is a program I've mocked up on my own, and is what the output should look like (forgive the funny source names):
![image](https://github.com/user-attachments/assets/db7d81b1-c9c1-4670-bd8f-ea7dd3de2873)

## Reproduction

1. Run the included example in HelloWorld
2. Attach Tracy
3. Note the occasional duplication of the events in the statistics menu

## Findings

As I'm a performance nut, I'm quite interested in the prospect of using Tracy, and so I've been screwing around with it a little bit.

I found that if I manually AllocHGlobal a never-released pointer of 'TracySourceLocationData*', fill it with data, and then pass it to the `TracyEmitZoneBegin(TracySourceLocationData* srcloc, int active)` binding, a given zone created with that data will never be duplicated in the statistics menu. That's actually how I got the example above.

Methinks something is wrong with either:
- `TracyAllocSrclocName` and potentially its variants, or
- `TracyEmitZoneBeginAlloc`

Intuitively I feel this shouldn't matter if you keep the CString pointers around, but I think something unhealthy is happening when P/Invoking an allocation of this struct as-shown in the examples. (Unrelatedly, TracyAllocSrclocName should return IntPtrs/nuints instead of ulongs, as the former will implicitly be the address-width of the host system)

**Comment by clibequilibrium** [comment]
> Hi again, I'm becoming the #1 issue maker on this repo it seems. ^^;
> 
> I've been referencing the new examples (and the previous ones before the CString oopsie) and I think there's something wrong with the way the zone contexts are instantiated.
> 
> ## Problem
> When recreating the "StartZone" method from the profiler class, I was getting weird inconsistencies in the color swatches within Tracy's Statistics menu. Occasionally they will create duplicates and randomly switch colors. They also don't appear to initially reflect the set color of the zone to begin with.
> 
> Here's an example: ![image](https://private-user-images.githubusercontent.com/9770110/372741163-fbb05817-925e-448e-aae9-893556c56c87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzU0NjUsIm5iZiI6MTcyNzg3NTE2NSwicGF0aCI6Ii85NzcwMTEwLzM3Mjc0MTE2My1mYmIwNTgxNy05MjVlLTQ0OGUtYWFlOS04OTM1NTZjNTZjODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTMxOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzcxOGE3NjVmZmNlZTA5MGYyODlkM2I0NzUwYTgxNDA3M2Q3OWMzOTJiNWFjNGQ0MWRiY2I3ODMxYmY4MGM5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8kvECn58wCxvSuwJLLpQu1yxjGr7UU6WTAHhnFW7KJo)
> 
> Here you can see that the "My Custom Event Name" event is a distinctly different shade of blue, and is duplicated twice over, with one being green. The ColoredEvent event doesn't match set zone color to begin with entirely.
> 
> The following picture is a program I've mocked up on my own, and is what the output should look like (forgive the funny source names): ![image](https://private-user-images.githubusercontent.com/9770110/372741811-db7d81b1-c9c1-4670-bd8f-ea7dd3de2873.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzU0NjUsIm5iZiI6MTcyNzg3NTE2NSwicGF0aCI6Ii85NzcwMTEwLzM3Mjc0MTgxMS1kYjdkODFiMS1jOWMxLTQ2NzAtYmQ4Zi1lYTdkZDNkZTI4NzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTMxOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNmYThkNGQ0MDY5OWE1YjdlMWJjOGE4NGFkZjVhYzhiODUzNDgyZjNiY2Y5ZjAxOTA5ZjdhMGI2YmUyNDZiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-s9hWMe6MOjrI4xqlhP4GEVZAEzf83trvguASJ4JWeE)
> 
> ## Reproduction
> 1. Run the included example in HelloWorld
> 2. Attach Tracy
> 3. Note the occasional duplication of the events in the statistics menu
> 
> ## Findings
> As I'm a performance nut, I'm quite interested in the prospect of using Tracy, and so I've been screwing around with it a little bit.
> 
> I found that if I manually AllocHGlobal a never-released pointer of 'TracySourceLocationData*', fill it with data, and then pass it to the `TracyEmitZoneBegin(TracySourceLocationData* srcloc, int active)` binding, a given zone created with that data will never be duplicated in the statistics menu. That's actually how I got the example above.
> 
> Methinks something is wrong with either:
> 
> * `TracyAllocSrclocName` and potentially its variants, or
> * `TracyEmitZoneBeginAlloc`
> 
> Intuitively I feel this shouldn't matter if you keep the CString pointers around, but I think something unhealthy is happening when P/Invoking an allocation of this struct as-shown in the examples. (Unrelatedly, TracyAllocSrclocName should return IntPtrs/nuints instead of ulongs, as the former will implicitly be the address-width of the host system)

Thanks for the report. Could you try to checkout this commit and please tell me if the issue also persists there? 
https://github.com/clibequilibrium/Tracy-CSharp/commit/a0bccba168e011883a29663e3068fcae9916707a

**Comment by BlueCyro** [comment]
> 
> Thanks for the report. Could you try to checkout this commit and please tell me if the issue also persists there? [a0bccba](https://github.com/clibequilibrium/Tracy-CSharp/commit/a0bccba168e011883a29663e3068fcae9916707a)

The issue still seems to be present, albeit significantly worse with this commit checked out: 
![image](https://github.com/user-attachments/assets/8320eac5-79d2-4b88-a90a-8dc6ac8b482d)

**Comment by BlueCyro** [comment]
I've done a bit more screwing around and it seems moreso like this is an issue with `TracyEmitZoneBeginAlloc`.

I think there are two problems:

1) Each time you call `TracyAllocSrclocName`, a brand new pointer is created and I can't track down where that pointer is actually freed on the C++ side. I think Tracy is getting confused when it sees a new zone allocation coming from a pointer that may or may not be the same when it's reallocated.
2) `TracyEmitZoneBeginAlloc` doesn't appear to like any pointer thrown into it to begin with

Using this information, I created my own allocation on the C# side with a pointer to unmanaged memory (tried AllocHGlobal, NativeMemory.Alloc, NativeMemory.AlignedAlloc) and attempted to pass that as the pointer instead. Tracy appears to not like that even more, and my C# program will outright hang in some cases without outputting an error.

Using `TracyAllocSrclocName` will allocate a chunk of memory that has the following structure:
```
2b  payload size
4b  color
4b  source line
fsz function name
1b  null terminator
ssz source file name
1b  null terminator
nsz zone name (optional)
```

While I haven't completely ruled out programmer error on either the repo's side or my own testing, I'm starting to wonder if maybe allocating zones this way is maybe broken on Tracy's side somehow. I've had solid success allocating zones with `TracyEmitZoneBegin` and passing it an unmanaged `TracySourceLocationData*` pointer. Allocating an unmanaged pointer to this struct and passing it along always results in no duplicate entries in the statistics menu every time I've done it this way.

**Comment by clibequilibrium** [comment]
Might be related to https://github.com/clibequilibrium/Tracy-CSharp/issues/44#issue-2571497039
I am releasing 0.11.1-hotfix to mitigate the issue

**Comment by Mervill** [comment]
I haven't seen the hotfix go live on nuget yet, but in my local testing this does appear to fix the issue.

**Comment by clibequilibrium** [comment]
> I haven't seen the hotfix go live on nuget yet, but in my local testing this does appear to fix the issue.

It took a bit for it to verify on NuGet side https://www.nuget.org/packages/Tracy-CSharp/0.11.1-hotfix
@BlueCyro  could you try to get the latest and confirm if the issue still persists? 

``dotnet add package Tracy-CSharp --version 0.11.1-hotfix``

**Comment by BlueCyro** [comment]
Can confirm that this fixes the issue. I've had it running for a bit now and it seems to function how I expect. Thanks!

**Comment by clibequilibrium** [comment]
> Can confirm that this fixes the issue. I've had it running for a bit now and it seems to function how I expect. Thanks!

Thanks for confirming. And thanks to @Mervill for spotting the reason.
