### ISSUE TITLE
The P/Invoke generator needs to be re-run.

### ISSUE THREAD

**Issue by Mervill** [clibequilibrium/Tracy-CSharp#44]
The `___tracy_alloc_srcloc` functions [now have a color argument](https://github.com/wolfpld/tracy/blob/90c072b66cd954585ce4dd82276dc7a323d9433c/public/tracy/TracyC.h#L211-L212) that aren't present in the generated C# bindings. I assume this is because the P/Invoke generator script hasn't been run since this argument was added.

I don't have CMake set up on my workstation otherwise I would attempt this myself.

Beyond simple correctness, this is relevant since the HelloWorld example will call the separate function `TracyEmitZoneColor` instead of using this argument when a color is provided to `BeginZone`. This means that BeginZone uses two interop calls when a color is specified when it could be using one interop call instead,

**Comment by clibequilibrium** [comment]
Thanks, added in https://github.com/clibequilibrium/Tracy-CSharp/commit/f58fb9c79e1aedd720a25d7b3d708160ab6f1220
